# Generated by Django 3.2.6 on 2021-08-12 00:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firstname')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Lastname')),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('user_type', models.CharField(choices=[('JS', 'Job Seeker'), ('EM', 'Employer')], default=0, max_length=200)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True)),
                ('description', models.CharField(max_length=500)),
                ('country', django_countries.fields.CountryField(default='KE', max_length=2)),
                ('location', models.CharField(max_length=20)),
                ('notice', models.CharField(choices=[('0', '0weeks'), ('1', '1 week'), ('2', '2 weeks'), ('3', '3 weeks'), ('4', '4 weeks'), ('5', 'more than a month')], default=0, max_length=200)),
                ('salary', models.CharField(blank=True, choices=[('confidential', 'Confidential'), ('0-5000', '0-5000'), ('5100-10000', '5100-10000'), ('10001-20000', '10001-20000'), ('20001-30000', '20001-30000'), ('30001-40000', '30001-40000'), ('40001-50000', '40001-50000'), ('50001 and above', '50001 and above')], default='confidential', max_length=30, null=True)),
                ('edeucation_level', models.CharField(choices=[('Phd', 'PHD'), ('masters', 'Masters'), ('degree', 'Bachelors Degree'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], default='entry', max_length=200)),
                ('job_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contract'), ('RT', 'Remote'), ('IT', 'Internship')], default='Full-Time"', max_length=200)),
                ('experience_length', models.CharField(choices=[('no', 'No Experience'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=200)),
                ('interview', models.CharField(choices=[('walkin', 'Walk-in'), ('remotely', 'remotely')], default='walkin', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
