# Generated by Django 3.2.6 on 2021-08-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='username'),
        ),
    ]
