# Generated by Django 3.2.6 on 2021-08-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApis', '0003_alter_job_edeucation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='edeucation_level',
            field=models.CharField(choices=[('Phd', 'PHD'), ('masters', 'Masters'), ('degree', 'Bachelors Degree'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], default='phd', max_length=200),
        ),
    ]
