# Generated by Django 3.2.6 on 2021-08-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApis', '0004_alter_job_edeucation_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='edeucation_level',
            new_name='education_level',
        ),
    ]
